version: '3.7'

services:
  web:
    build: 
      context: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    env_file:
      - .env
    networks:
      - postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14.4
    restart: always
    networks:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: ${POSTGRES_PG_DATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pddata:${POSTGRES_PG_DATA}
networks:
  postgres:
volumes:
  pddata:
